name: dart_admin
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Warren Strange <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  firebase_admin_interop: ^2.0.0


dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0
  test: ^1.0.0
  pedantic: any
  build_test:
