name: golf_functions
description: Test Firebase Functions Interop
version: 0.0.0
#homepage: https://www.example.com
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  firebase_functions_interop: ^1.0.0


dev_dependencies:
  build_runner: ^1.0.0
  build_node_compilers: ^0.2.0