#
database:
  username: dart
  password: dart
  host: localhost
  port: 5432
  databaseName: dart_test

#
#database:
#  username: "postgres"
#  password: "postgres"
#  host: "localhost"
#  port: 5432
#  databaseName: "golf"