
DROP DATABASE golf;

CREATE DATABASE golf
    WITH
    OWNER = dart
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE golf TO dart;

GRANT TEMPORARY, CONNECT ON DATABASE golf TO PUBLIC;
